#!/bin/bash
export API_KEY_BIN="YOUR API KEY BINANCE"
export API_SECRET_BIN="YOUR SECRET KEY BINANCE"
export TOKEN_TB="YOUR TELEGRAM BOT TOKEN FOR NOTIFICATION MESSAGE"
export TOKEN_TB_ERROR="YOUR TELEGRAM BOT TOKEN FOR ERROR MESSAGE"
export CHAT_ID_TB="CHAT ID TELEGRAM BOT"
source /home/.env/bin/activate
python /home/part-trade-bot/bot_ALPHABTC/start.py
